name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*' # 例如 v1.0.0 时触发

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -ldflags "-s -w" -trimpath \
          -o dist/proxy-manager_${{ matrix.goos }}_${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: binaries-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/
          if-no-files-found: error

  release-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Create Tag Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  && github.event_name == 'push'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          path: dist

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Nightly Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete nightly -y || true
          
          gh release create nightly \
            $(find dist -type f) \
            --title "Nightly Release" \
            --notes "Automatically built from master commit $GITHUB_SHA on $(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
            --prerelease